### ISSUE TITLE
Integration for different AndroidOS's

### ISSUE THREAD

**Issue by Real-Troglodyte** [Real-Troglodyte/Aquadroid.apk#7]
Integration to create more easy using on aquadroid.apk.

Plans :

- reduce lags (done) 
- remove crashes (done) 
- better dip detection (done) 
- ime solutions (done) 
- code menu interactive interface (done) 
- smoother translation (done) 
- scrollable navbar (unplanned) 
- General bug fixes (done) 
- New CoreUI supports (done) 
- new AquaUI interface (done) 
- Android 13+ support (4 years) (done) 
- removing support for android 8 and below (done for newer versions) 
- easier plugins manager (done) 
- correct "Plugins" tab error message (done) 
- Better dark mode
- Battery saver options
- More spoof settings

**Comment by Accelium** [comment]
How do you contribute

**Comment by Real-Troglodyte** [comment]
Ask questions in the "discussions" tab, this is irrelevant to this issue
